#!/usr/bin/python3

import argparse
import asyncio
import random
import sys
import threading
import time
from typing import Generator, Optional

import pyaudio

from stim.pattern import ChaosPulses, Pattern, PatternSequence, Pulses, Silence, Wave
from stim.player import Player, WaveWriter


class Stim(Player, threading.Thread):
    def __init__(self) -> None:
        super().__init__()
        self.audio = pyaudio.PyAudio()
        self.stream: Optional[pyaudio.Stream] = None
        self.shutting_down = False

    async def loop(self):
        self.start()
        while not self.channels[0].ended:
            await asyncio.sleep(1)

    def shutdown(self):
        print("shutting down")
        self.shutting_down = True
        if self.stream:
            while self.stream.is_active():
                time.sleep(0.1)
            self.stream.stop_stream()
            self.stream.close()
        self.join()

        self.audio.terminate()

    def _stream_callback(self, in_data, frame_count: int, time_info, status) -> tuple[bytes, int]:
        if self.shutting_down:
            return bytes(), pyaudio.paComplete
        return self.get_samples(frame_count).tobytes(), pyaudio.paContinue

    def run(self):
        # for paFloat32 sample values must be in range [-1.0, 1.0]
        self.stream = self.audio.open(
                format=pyaudio.paFloat32,
                channels=len(self.channels),
                rate=self.sample_rate,
                output=True,
                # See https://stackoverflow.com/questions/31391766/pyaudio-outputs-slow-crackling-garbled-audio
                frames_per_buffer=4096,
                stream_callback=self._stream_callback)


class PulseWaveEscalateBase(PatternSequence):
    PULSE_VOLUME = 0.9
    WAVE_VOLUME = 1
    # MIN_DURATION = 0
    MIN_DURATION = 20
    # START = 1
    START = 20

    def duration_pattern(self) -> Generator[float, None, None]:
        yield from range(self.START, 20)
        for i in range(20, 30):
            yield i
            yield i
        while True:
            yield 30

    def freq_pattern(self) -> Generator[float, None, None]:
        while True:
            yield random.choice([1000, 2000, 5000])


class PulseWaveEscalate(PulseWaveEscalateBase):
    def __init__(self):
        super().__init__("pulse wave escalate")

    def patterns(self) -> Generator[Pattern, None, None]:
        for i, f in zip(self.duration_pattern(), self.freq_pattern()):
            yield Pulses(count=i * 2, duration=0.1, freq=f, volume=self.PULSE_VOLUME, gap=5.0/100.0)
            yield Wave(volume=self.WAVE_VOLUME, duration=self.MIN_DURATION + i / 2, freq=f)
            yield Silence(duration=5.0/100.0)


class PulseWaveEscalateChaotic(PulseWaveEscalateBase):
    FREQ = 1000

    def __init__(self):
        super().__init__("pulse wave escalate with chaotic pulses")

    def patterns(self) -> Generator[Pattern, None, None]:
        for i, f in zip(self.duration_pattern(), self.freq_pattern()):
            yield ChaosPulses(count=i * 2, duration=(0.1, 0.3), freq=(200, 5000), volume=(0.7, 1, 1), gap=5.0/100.0)
            yield Wave(volume=self.WAVE_VOLUME, duration=self.MIN_DURATION + i / 2, freq=self.FREQ)
            yield Silence(duration=5.0/100.0)


class PulseWaveEscalate2(PulseWaveEscalateBase):
    FREQ = 1000
    PULSE_VOLUME = 1.0

    def __init__(self):
        super().__init__("pulse wave escalate 2")

    def patterns(self) -> Generator[Pattern, None, None]:
        for i in self.duration_pattern():
            yield Pulses(count=i * 2, duration=0.6, freq=self.FREQ, volume=self.PULSE_VOLUME, gap=10.0/100.0)
            yield Wave(volume=self.WAVE_VOLUME, duration=i, freq=self.FREQ)
            yield Silence(duration=5.0/100.0)


class VolumeSwing(PatternSequence):
    def __init__(self):
        super().__init__("frequency swing")

    def patterns(self) -> Generator[Pattern, None, None]:
        while True:
            for volume in range(50, 100, 5):
                yield Wave(volume=volume / 100.0, duration=0.1, freq=220)
            yield Wave(volume=1, duration=5, freq=220)
            for volume in range(100, 50, -5):
                yield Wave(volume=volume / 100.0, duration=0.1, freq=220)
            yield Wave(volume=0.5, duration=2, freq=220)


class FrequencyDifference(PatternSequence):
    def __init__(self):
        super().__init__("frequency swing")

    def patterns(self) -> Generator[Pattern, None, None]:
        while True:
            # yield Wave(volume=1.0, duration=1, freq=200)
            yield Wave(volume=1.0, duration=1, freq=1000)


class Caress(PatternSequence):
    FREQ = 1000

    def __init__(self):
        super().__init__("caress")

    def patterns(self) -> Generator[Pattern, None, None]:
        yield Wave(volume=0.3, duration=0.5, freq=self.FREQ)
        peak_size = 1
        while True:
            for i in range(60, 100):
                yield Wave(volume=i / 100.0, duration=i / 1000.0, freq=self.FREQ)
            yield Wave(volume=1, duration=peak_size, freq=self.FREQ)
            peak_size = min(peak_size + 1, 10)
            for i in range(100, 60, -3):
                yield Wave(volume=i / 100.0, duration=i / 1000.0, freq=self.FREQ)


class Calibrate(PatternSequence):
    FREQ = 1000.0

    def __init__(self):
        super().__init__("calibration tune")

    def patterns(self) -> Generator[Pattern, None, None]:
        while True:
            yield Wave(volume=1.0, duration=10, freq=self.FREQ)


class FrequencySwing(PatternSequence):
    def __init__(self):
        super().__init__("frequency swing")

    def patterns(self) -> Generator[Pattern, None, None]:
        for freq in range(50, 1000, 100):
            yield Wave(volume=1.0, duration=1, freq=freq)


class RandomPulseWave(PatternSequence):
    def __init__(self):
        super().__init__("random")

    def patterns(self) -> Generator[Pattern, None, None]:
        import random
        while True:
            yield Pulses(count=random.randrange(2, 20), duration=0.1, freq=200.0, volume=0.9, gap=5.0/100.0)
            yield Wave(volume=1.0, duration=random.randrange(1, 15) / 2.0, freq=220.0)
            yield Silence(duration=5.0/100.0)


class NumberSequencePulseWave(PatternSequence):
    FREQ = 1000

    def __init__(self, number: str):
        super().__init__(f"random {number}")
        self.number = number

    def patterns(self) -> Generator[Pattern, None, None]:
        while True:
            for val in [int(n) for n in self.number]:
                yield Pulses(count=val, duration=0.1, freq=self.FREQ, volume=0.9, gap=5.0/100.0)
                yield Wave(volume=1.0, duration=val, freq=self.FREQ)
                yield Silence(duration=5.0/100.0)


class RandomPauseWave(PatternSequence):
    FREQ = 1000

    def __init__(self):
        super().__init__("wave with random pause")

    def patterns(self) -> Generator[Pattern, None, None]:
        import random
        yield Wave(volume=0.3, duration=0.3, freq=self.FREQ)
        yield Wave(volume=0.6, duration=0.3, freq=self.FREQ)
        while True:
            yield Wave(volume=1.0, duration=random.randrange(1, 10), freq=self.FREQ)
            yield Silence(duration=random.uniform(3.0/10.0, 1))


async def amain(player: Player):
    await player.loop()


def main():
    # TODO: allow to use a function for intensity
    # TODO: implement a slow start

    parser = argparse.ArgumentParser(description="Tone pattern generator")
    parser.add_argument("-o", "--output", action="store", metavar="file.wav",
                        help="write the generated audio to the given file instead of playing it")
    parser.add_argument("-c", "--calibrate", action="store_true",
                        help="play a constant full volume calibration sound")
    args = parser.parse_args()

    if args.output:
        player = WaveWriter(args.output)
    else:
        player = Stim()

    try:
        if args.calibrate:
            player.start_mono(Calibrate())
        else:
            # player.start_mono(PulseWaveEscalate())
            # player.start_mono(PulseWaveEscalateChaotic())
            player.start_stereo(
                    left=PulseWaveEscalate(),
                    # left=PulseWaveEscalateChaotic(),
                    # left=RandomPauseWave(),
                    # right=RandomPauseWave())
                    # right=FrequencySwing())
                    right=PulseWaveEscalateChaotic())
            # player.start_mono(PulseWaveEscalate2())
            # player.start_mono(FrequencySwing())
            # player.start_mono(FrequencyDifference())
            # player.start_mono(Caress())
            # player.start_mono(RandomPulseWave())
            # player.start_mono(RandomPauseWave())
            # player.start_mono(NumberSequencePulseWave("1234124312"))
            # player.start_stereo(left=FrequencySwing(), right=FrequencySwing())
            # player.start_stereo(
            #         left=PulseWaveEscalate(),
            #         right=VolumeSwing(),
            # )

        asyncio.run(amain(player))
        print("AMAIN END")
    except KeyboardInterrupt:
        print("Shutting down...")
    finally:
        print("CLEANUP")
        player.shutdown()


if __name__ == "__main__":
    sys.exit(main())
