#!/usr/bin/python3

import argparse
import logging
import sys

import pyeep.aio
import pyeep.app
import pyeep.gtk
from pyeep.gtk import Gtk
from stim import cnc, scenes, toy
from stim.toy_gtk import ToysView
from stim.output import NullOutput, NewOutput

log = logging.getLogger(__name__)


class App(pyeep.gtk.GtkApp, pyeep.aio.AIOApp):
    def __init__(self, args: argparse.Namespace, **kwargs):
        super().__init__(args, **kwargs)

        self.toys_view = self.add_component(ToysView)

        self.add_component(toy.Toys, client_name=self.title, iface=args.iface)
        self.add_component(cnc.CncReceiver)
        null_output = self.add_component(NullOutput, name="null_output")
        self.send(NewOutput(output=null_output))

    def build_main_window(self):
        super().build_main_window()

        self.grid = Gtk.Grid()
        self.window.set_child(self.grid)

        self.frame_inputs = Gtk.Frame(label="Inputs")
        self.frame_inputs.set_child(self.toys_view)
        self.toys_view.set_vexpand(True)

        self.frame_outputs = Gtk.Frame(label="Outputs")
        self.frame_scenes = Gtk.Frame(label="Scenes")
        self.scenes_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.frame_scenes.set_child(self.scenes_box)

        self.frame_log = Gtk.Frame(label="Log")
        self.frame_log.set_child(self.logview)
        self.logview.set_vexpand(True)

        self.grid.attach(self.frame_inputs, 0, 0, 1, 1)
        self.grid.attach(self.frame_outputs, 0, 1, 1, 1)
        self.grid.attach(self.frame_scenes, 1, 0, 1, 2)
        self.grid.attach(self.frame_log, 0, 2, 2, 1)

        # Actions for scenes
        action = pyeep.gtk.Gio.SimpleAction.new("eagerness", None)
        action.connect("activate", self.start_scene, scenes.Eagerness)
        self.gtk_app.add_action(action)

        scenes_menu = pyeep.gtk.Gio.Menu()
        scenes_menu.append("Eagerness", "app.eagerness")

        menu = pyeep.gtk.Gio.Menu()
        menu.append_submenu("Scenes", scenes_menu)
        self.gtk_app.set_menubar(menu)
        self.window.set_show_menubar(True)

    def start_scene(self, action, param, scene):
        component = self.add_component(scene)
        self.scenes_box.append(component)

    def ui_main(self):
        self.head.start()
        super().ui_main()


def main():
    parser = App.argparser("Play with nonconventional inputs and outputs")
    parser.add_argument("-i", "--iface", metavar="address", action="store", default="ws://127.0.0.1:12345",
                        help="Intiface Engine address to connect to")
    args = parser.parse_args()

    with App(args, title="Player", application_id="org.enricozini.play") as app:
        app.main()


if __name__ == "__main__":
    sys.exit(main())
